### ISSUE TITLE
Preparing new data for testing

### ISSUE THREAD

**Issue by shraghuna** [thunlp/KNET#2]
I wish to use kNet (the provided model) on some custom test data. How should I prepare the data for the classifier? The data is raw text (different lines of a conversation).
Any help would be greatly appreciated.

**Comment by ji-xin** [comment]
Hello, thank you for your interest.

I suggest using `numpy.load()` to check `test_{entity, context, label}.npy`. It should be easy to figure out how to convert raw text data into `numpy.array` of the same format. Then `numpy.save()` can be use to save your data into `.npy` files.

Please refer to [Issue 1](https://github.com/thunlp/KNET/issues/1) for details of `*_context.npy` files.

As for `*_fbid.npy` and `link_*.npy` files, they are for other experiments to further evaluate the model (details are in the paper). You can simply use `numpy.zeros()`, with proper shapes, for your dataset. The output of entity typing as well as overall performance would not be affected (they only affect the performance on the correct/erroreous subsets).
