### ISSUE TITLE
Hi, Can you please explain what do files starting with link contain?

### ISSUE THREAD

**Issue by rijula** [thunlp/KNET#4]

**Comment by ji-xin** [comment]
In Section 5.4 of the paper (Disambiguation difficulty part), entities in subsets _correct_ and _errorneous_ are evaluated separately. These `link*` files actually record which entities are linked successfully and therefore should be in the _correct_ subset (based on the parameters given in `paper_parameter/` folder)

Ignoring these files will not affect type classification itself, but will probably gives you wrong results when you wish to explore these two subsets.

**Comment by rijula** [comment]
Hi, Thank you for your explanation. Can you please share the disamb file for training dataset part? It would be really helpful for our further analysis and research.

**Comment by ji-xin** [comment]
It's in the `data` folder, `disamb_file.gz`.

**Comment by rijula** [comment]
Hi,
Thank you for your reply. As far as I understand ,data/disamb_file.gz only contains the disambiguated entities for testing data, not for training data. And for your paper, you have taken different training and testing entities.

**Comment by ji-xin** [comment]
Yes you are right; sorry for the confusion.

It turns out that in the training step we do not need the disamb data. Disamb data are used for making a better "reconstructed entity embedding", which is a critical step in evaluation. However, we already know the entity embedding in the training step, so it's not necessary.

**Comment by rijula** [comment]
Hi,
I have one more query. Can you please provide the mapping file from freebase types to your types, so that we can use it for our further research?

**Comment by ji-xin** [comment]
[types.mapping.txt](https://github.com/thunlp/KNET/files/2092338/types.mapping.txt)
