### ISSUE TITLE
关于train_context文件的疑问

### ISSUE THREAD

**Issue by airkid** [thunlp/KNET#5]
作者您好，我打印了train_context[0]，内容如下：

['95' 'They' '1992' 'arrived' 'the' 'in' 'during' 'Bosnia' 'side' 'and'
 'Bosniak' 'Herzegovina' 'the' 'with' 'on' 'the' 'fought' 'aim' 'who' 'of'
 'volunteers' 'fighting' 'Muslim' 'for' 'foreign' 'Islam' 'were' 'and'
 'ahid' 'on']
其对应的train_entity[0]的值为['Bosnian', 'War']

该list包含了30个词，我想是对应着文章在提到的window_size=15
但是看起来这段list中的单词并未保持原句的顺序，请问
1.为何会使用乱序的方式存储context，有什么特别原因吗？
2.乱序的context会对模型性能产生影响吗？（我认为是会的，因为后面要输入进LSTM网络中）

**Comment by ji-xin** [comment]
#1

**Comment by airkid** [comment]
谢谢！
